apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

# this manageNodeGroups are completly managed by AWS and normal NodeGroups are managed by us.
managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 3
    spot: true